Bin Exploit
thecyberworld/TheCyberHUB pull request #630
Opened 2024-02-05 09:39 UTC by Saedbhati

## Fixes Issue

## Changes proposed

## Screenshots

## Note to reviewers

## Code of Conduct

- [ ] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

2024-02-06 20:29 UTC, ArkadiK94 commented
@Saedbhati could you fill the pr description and add here screen shot/ short video? (not in discord so it will be easier to match it with the pr)

2024-02-07 12:44 UTC, Saedbhati commented
![image](https://github.com/thecyberworld/TheCyberHUB/assets/105969318/353640fb-f075-47db-96e1-df732fff3580)
![image](https://github.com/thecyberworld/TheCyberHUB/assets/105969318/c0ceb154-6c1f-4bc4-92e8-b2acbbab4c38)

sorry

2024-02-07 17:35 UTC, ArkadiK94 commented
@Saedbhati 
1. make an active button in color orange (#ff6b08)
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/a44c83c8-e9dd-4eb2-86e1-3a566b1efc3b)

2. too much buttons that I can click on them, maybe leave only the upper buttons as buttons and the ones in right side of the BinExploits as text and structure it in table with titles for each column.
3. remove this arrow, we in browser, or make it in different way (in the left site of the window/bigger etc.) because it feels strange 
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/f7920cc2-4ebd-47c8-b508-755e8788bb00)

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/8d66df7a-f378-415b-8465-cb10f29de7e8

2024-02-07 18:29 UTC, ArkadiK94 requested changes
@Saedbhati overall looks great 👍 . I have some review comments.

2024-02-07 18:29 UTC, ArkadiK94 commented on src/components/GTFOBins/GtfoMain.jsx
> +                    Object.keys(data).map((keys) => {
better to change to `key` instead of `keys` ,because you get all the keys and iterate over every key.

2024-02-07 18:29 UTC, ArkadiK94 commented on src/components/GTFOBins/GtfoMain.jsx
> +                                        {Object.keys(data[keys].functions).map((function_) => (
what do you say about `binaryFunction` instead of `function_`? or even "func" as you did later on

2024-02-07 18:29 UTC, ArkadiK94 commented on src/components/GTFOBins/GtfoMain.jsx
> +                        return null;
if you `return null` so you should not use map() you can use forEach() instead , in my opinion

2024-02-07 18:29 UTC, ArkadiK94 commented on src/components/GTFOBins/DataPages.jsx
> +                        <p>{FunctionData[data].description}</p>
You have two files of data : `Data.jsx` and `_gtfoJson.jsx` 
Why do you have a `description` property in Data.jsx if you don't use it anywhere?
Did you intend to use it somewhere else? if not, in my opinion , you should remove this info.

2024-02-07 18:29 UTC, ArkadiK94 commented on src/components/GTFOBins/DataPages.jsx
> +                            <code>{Data[0][id].functions[data][0].code}</code>
Why do you display only first element of array and not all of them? are they less important for user to know?

2024-02-08 03:48 UTC, Saedbhati commented
ok let me fix the problem

2024-02-09 14:21 UTC, ArkadiK94 commented
1. too much buttons that I can click on them, maybe leave only the upper buttons as buttons and the ones in right side of the BinExploits as text and structure it in table with titles for each column. -> @kabir0x23 let's leave it as he did for now?
2. remove this arrow, we in browser, or make it in different way (in the left site of the window/bigger etc.) because it feels strange ->  @kabir0x23 let's leave it as he did for now?

![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/f7920cc2-4ebd-47c8-b508-755e8788bb00)

2024-02-09 14:41 UTC, ArkadiK94 approved these changes
@Saedbhati Great Work 💯 
Only change the name of the file `Function.jsx` to `binExploitsFunctionsData.jsx` as well `Data.jsx` file to `binExploitsData.jsx`.

2024-02-09 20:42 UTC, ArkadiK94 commented
@Saedbhati @kabir0x23 by the way, is it related to any open issue?

2024-02-10 07:05 UTC, kabir0x23 commented
> @Saedbhati @kabir0x23 by the way, is it related to any open issue?

yes, #498

2024-02-10 09:11 UTC, ArkadiK94 commented
>1. too much buttons that I can click on them, maybe leave only the upper buttons as buttons and the ones in right side of the BinExploits as text and structure it in table with titles for each column. -> @kabir0x23 let's leave it as he did for now?
>2. remove this arrow, we in browser, or make it in different way (in the left site of the window/bigger etc.) because it feels strange -> @kabir0x23 let's leave it as he did for now?
>Only change the name of the file Function.jsx to binExploitsFunctionsData.jsx as well Data.jsx file to binExploitsData.jsx.


@kabir0x23 Can we merge this pr, or do you want him to make the changes that I wrote above?

2024-02-10 10:37 UTC, merged