Methodology
thecyberworld/TheCyberHUB pull request #657
Opened 2024-02-13 16:36 UTC by Saedbhati

## Fixes Issue

## Changes proposed

## Screenshots
![image](https://github.com/thecyberworld/TheCyberHUB/assets/105969318/22566f94-3f01-4c23-9ac5-8ad2134e3ed2)

## Note to reviewers

## Code of Conduct

- [ ] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

2024-02-13 18:03 UTC, ArkadiK94 requested changes
@Saedbhati Looks great, I have some comments.
@kabir0x23 I need you opinion on one comment about the path.

2024-02-13 18:03 UTC, ArkadiK94 commented on src/components/Resources/Methodology/MethodologyElement.jsx
> +export const CategoryHeading = styled.h1`
You don't use it anywhere, so or use it, or delete this file.

2024-02-13 18:16 UTC, ArkadiK94 commented on src/components/Resources/Methodology/MethodologyMain.jsx
> +    function handleClick(id) {
@kabir0x23 what do you think?

2024-02-13 18:17 UTC, kabir0x23 commented on src/App.jsx
> +                        <Route path={"/resources/methodology"} element={<Methodology />} />
yes correct, those should be in the /resources path

2024-02-13 18:39 UTC, ArkadiK94 commented on src/App.jsx
> +                        <Route path={"/resources/methodology"} element={<Methodology />} />
Ok, so I resolve this comment, and we need to make changes in the other pages as well.

2024-02-13 23:24 UTC, ArkadiK94 commented on src/components/Resources/Methodology/MethodologyMain.jsx
> +    function handleClick(id) {
https://www.reddit.com/r/reactjs/comments/zvqhku/what_is_the_equivalent_of_documentgetelementbyid/?rdt=41932

2024-02-14 06:16 UTC, Saedbhati commented
Ok I will

2024-02-14 12:28 UTC, ArkadiK94 commented on src/components/Resources/Methodology/MethodologyMain.jsx
> +                {Object.keys(MethodologyData).map((data) => (
Need to update all the places where this parameter is used

2024-02-14 12:28 UTC, ArkadiK94 commented on src/components/Resources/Methodology/MethodologyMain.jsx
> +                        {Object.keys(MethodologyData[data].Topics).map((Topics) => (
Need to update all the places where this parameter is used

2024-02-14 12:29 UTC, ArkadiK94 commented on src/components/Resources/Methodology/MethodologyMain.jsx
> +                                {Object.keys(MethodologyData[data].Topics[Topics]).map((SubTopics) => (
Need to update all the places where this parameter is used

2024-02-14 12:29 UTC, ArkadiK94 commented on src/components/Resources/Methodology/MethodologyMain.jsx
> +                                                    (Goals) => (
Need to update all the places where this parameter is used

2024-02-16 20:00 UTC, ArkadiK94 commented on src/components/Resources/Methodology/MethodologyMain.jsx
> +                                                borderTop: "0.5px solid white",
@Saedbhati Did you miss this comment? do you have a different opinion regarding it?

2024-02-16 20:07 UTC, ArkadiK94 approved these changes
@Saedbhati Excellent 💯 Only one minor comment left that you didn't reply about / make changes.

2024-02-17 03:13 UTC, Saedbhati commented
@ArkadiK94  sorry i may have overlook it but i have updated the code u check

2024-02-17 18:49 UTC, merged