Add feature: Mobile Layout, Dispaly SubMenu
thecyberworld/TheCyberHUB pull request #714
Opened 2024-03-17 05:56 UTC by AbdullahAli420

## Fixes Issue #576 

## Changes proposed
See video!

## Screenshots
Old:-

https://github.com/thecyberworld/TheCyberHUB/assets/118581404/0353ea16-acc8-4bbf-b69e-cdb0c8acc18c

Fixed:-

https://github.com/thecyberworld/TheCyberHUB/assets/118581404/ec557eb2-c3e8-4bdb-acaf-542964903133

## Note to reviewers
Feel free to tell me any changes you want!

## Code of Conduct

- [ ] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

2024-03-19 08:27 UTC, ArkadiK94 commented
@AbdullahAli420 Very important, before submitting your code. You should check the console (you have two errors):

![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/2bbd6f96-19a4-4e6d-bd82-5ec77ed2db92)

2024-03-19 08:37 UTC, ArkadiK94 commented
before
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/abde7912-ef74-4a9d-9c13-d01b4168a9ae)

after
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/cafefbac-713c-4dae-b93e-6c1647f14509)

the menu on media range : 822-1150 not responsive as it was before your changes

in addition, your new sub tabs not happens on media range : 769-821
769:
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/f6042ed2-0884-449f-baf8-831d6872e5e0)
768:
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/9130aef1-5129-4a53-83a8-b81e960c7003)

2024-03-19 08:42 UTC, ArkadiK94 requested changes
@AbdullahAli420 Thank you for your contribution, please, fix the comments that I wrote.

2024-03-19 12:15 UTC, ArkadiK94 commented
@AbdullahAli420 Great, I tried it out, and one more issue,
when I click first tab the sub tabs open, when I click different tab the sub tabs of previous tab close but the sub tabs of the different tab are not opened

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/ff0ccf0f-4693-4572-b38b-b37be14b7b34

2024-03-20 08:40 UTC, AbdullahAli420 commented
Done check that.

2024-03-20 19:42 UTC, ArkadiK94 approved these changes
@AbdullahAli420 Looks great and thank you for your contribution 👍 
I have one last minor comment.

2024-03-20 19:42 UTC, ArkadiK94 commented on src/components/Header/Dropdowns/DropdownElements.jsx
> +        // width: min-content;
if you don't use it, remove it.

2024-03-20 19:42 UTC, ArkadiK94 commented on src/components/Header/Navbar/NavbarElements.jsx
> +    // display: none;
if you don't use it, remove it , I am writing here, but I refer to all commented styles that you don't use.

2024-03-20 19:44 UTC, ArkadiK94 commented
@AbdullahAli420 I will merge the pr because it is not a big deal, but for next time, please don't leave commented styles that you don't need to use :)

2024-03-20 19:44 UTC, merged

2024-03-21 07:14 UTC, AbdullahAli420 commented
Ok I will take care of that.