Prevent form submit if text is empty
thecyberworld/TheCyberHUB pull request #757
Opened 2024-04-25 16:25 UTC by Tamir198

Closed #756, now you can`t submit the button if the text is empty : 

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/b2f3931e-08c3-47dd-9419-07297934d139)

2024-04-25 20:06 UTC, ArkadiK94 requested changes
@Tamir198  When the user wants to add empty Goal the input box should become red and toast validation/error message by using the toastify library - which already installed in the project. To give indication to the user.

2024-04-27 12:31 UTC, Tamir198 commented
Now this is what you see as an error indicator : 

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/d119cd1e-e017-4d94-82f6-6784153ac8c2)


To `GoalInput` with the styled component I had to add some styles because the CSS files overrated them.

2024-04-27 14:05 UTC, ArkadiK94 approved these changes
@Tamir198  Thanks, looks great 👍 
Only one last change.

2024-04-27 14:05 UTC, ArkadiK94 commented on src/components/Dashboard/OldDashbaord/GoalSetter/GoalForm.jsx
> +            toast("Cannot submit empty goal");
```suggestion
            toast.warn("Cannot submit empty goal");
```
It will look better for this toast message

2024-04-27 14:10 UTC, merged