Style: AddCommentForm changed
thecyberworld/TheCyberHUB pull request #767
Opened 2024-04-28 19:45 UTC by Saifmagouri

## Fixes Issue

## Changes proposed

Improved the styling of the `AddCommentForm` component to enhance usability and user-friendliness.

## Screenshots

![Capture d'écran 2024-04-28 185926](https://github.com/thecyberworld/TheCyberHUB/assets/114822491/27697142-0543-4a55-a129-74d35a053bed)
![Capture d'écran 2024-04-28 204258](https://github.com/thecyberworld/TheCyberHUB/assets/114822491/4936fb32-1d89-4818-8654-f9564a05b5f3)
![Capture d'écran 2024-04-28 204251](https://github.com/thecyberworld/TheCyberHUB/assets/114822491/d080e7aa-66eb-4ac2-938e-21fb0306df33)

## Note to reviewers

## Code of Conduct

- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/TheCyberHUB/blob/dev/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

2024-04-28 19:59 UTC, ArkadiK94 commented
@Saifmagouri you staged fileupload.md removal. Remove from git this change.

2024-04-28 20:20 UTC, ArkadiK94 commented
@Saifmagouri tell me if you need help with it

2024-04-28 20:44 UTC, Saifmagouri commented
@ArkadiK94 fileupload.md was removed automatically because my antivirus was trigerred 
what should i do to complete the PR

2024-04-28 20:50 UTC, Saifmagouri commented
@ArkadiK94 okay i will keep it in mind next time

2024-04-29 09:59 UTC, ArkadiK94 requested changes
@Saifmagouri Thanks for your contribution, I have some comments.

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/4b5a2d66-a8c1-4594-a001-3e6b3347567d

1. the style of the "Submit" button, do similar as in INTERNSHIP OPPORTUNITIES form

2. add border to the input box also as in INTERNSHIP OPPORTUNITIES form

3. also the border color of the comment box change it to be grey

2024-04-29 09:59 UTC, ArkadiK94 commented on src/components/Blogs/BlogComments/AddCommentForm.jsx
> +            )}
@Saifmagouri nope delete it and use toast.warn method from "react-toastify" package

2024-05-02 20:04 UTC, ArkadiK94 requested changes
@Saifmagouri Hi, looks much better but please, fix the new comment.

2024-05-02 20:04 UTC, ArkadiK94 commented on src/components/Other/MixComponents/Buttons/ButtonElements.jsx
@Saifmagouri very problematic, you made a major changes without checking all the places where this button is used

![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/cdb9f8aa-997e-4e45-91a4-4f97a21f7e71)

For example:
Before the change:
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/1e18e22f-4f97-4768-ac19-14b67c339376)

After the change:
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/97fe23cb-1987-46fc-80d2-92603fd506b1)
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/a311576f-dc97-483a-a6ef-47eec8a3510b)

Next, time always if you want to change existed component make sure to check where it used 

Now:
1. create local component button style
2. adjacent the changes to the right ones in all places!

2024-05-08 20:50 UTC, ArkadiK94 commented
@Saifmagouri hi, how is it going?

2024-05-11 20:31 UTC, ArkadiK94 commented
Because there is no response, I will modify it by myself...

2024-05-16 18:32 UTC, ArkadiK94 commented
@Saifmagouri Thank you very much for your contribution, I resolved the last comment.

2024-05-16 18:32 UTC, ArkadiK94 approved these changes

2024-05-16 18:32 UTC, merged