Add upload form
thecyberworld/TheCyberHUB pull request #860
Opened 2024-06-12 18:09 UTC by Tamir198

Fix issue #841 

This is the form (right now not connected to any backend) : 

https://github.com/thecyberworld/TheCyberHUB/assets/34707669/1a0efe34-fae2-421c-b4dd-1f7a20705936

Right now, the Zod validation validates things in a kind of "hardcoded way," but since the maximum number of answers won't change often, I think it's okay. I can think of other solutions if we want to implement dynamic answer numbers.

Also, it`s not in the video but there is a check for the minimum question length : 

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/f09461e5-005b-49c4-9dbf-d451214886b1)

2024-06-14 18:02 UTC, ArkadiK94 requested changes
@Tamir198 Thank you very much 👍 
I have some comments.

2024-06-22 16:39 UTC, Tamir198 commented on src/components/Feeds/FeedPoll/uploadPollForm/FormInput.jsx
> +                <StyledInput errorMessage={errorMessage} placeholder={placeholder} {...register(name)} />
Chagned

2024-06-22 16:40 UTC, Tamir198 commented on src/components/Feeds/FeedPoll/uploadPollForm/FormInput.jsx
> +    border: ${({ errorMessage }) => (errorMessage ? "1px solid #d32f2f" : "1px solid #555")};
Changed

2024-06-22 16:40 UTC, Tamir198 commented on src/components/Feeds/FeedPoll/uploadPollForm/UploadPollForm.jsx
> +import { z } from "zod";
Nice idea but if you wont force this in a every pr you will get mixed names

2024-06-22 16:42 UTC, Tamir198 commented on src/components/Feeds/FeedPoll/uploadPollForm/UploadPollForm.jsx
> +    answer3: z.string().min(4, ANSWER_ERROR_MSG).optional(),
I think answer because in your polls we ask some quesiton

2024-06-22 16:42 UTC, Tamir198 commented on src/components/Feeds/FeedPoll/uploadPollForm/UploadPollForm.jsx
> +    const MAX_ANSWERS = 3;
Done

2024-06-22 16:43 UTC, Tamir198 commented on src/components/Feeds/FeedPoll/uploadPollForm/UploadPollForm.jsx
> +                errorMessage={errors?.question?.message}
Yes, try to submit short question

2024-06-23 18:12 UTC, ArkadiK94 commented on src/components/Feeds/FeedPoll/uploadPollForm/UploadPollForm.jsx
> +import { z } from "zod";
You right, let's leave it "z"

2024-09-06 14:50 UTC, closed without merging